- name: Configurar servidor web con Apache
  hosts: all
  become: yes

  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Habilitar e iniciar Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Crear página web de bienvenida con estilo
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html lang="es">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Bienvenido a Vagrant</title>
              <style>
                  body {
                      font-family: 'Poppins', sans-serif;
                      background-color: #1e1e1e;
                      color: #ffffff;
                      text-align: center;
                      margin: 0;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      height: 100vh;
                  }
                  .container {
                      background: #2c2c2c;
                      padding: 30px;
                      border-radius: 12px;
                      box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.3);
                      max-width: 500px;
                  }
                  h1 {
                      color: #ffcc00;
                  }
                  p {
                      font-size: 1.2em;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🚀 Servidor en Ansible 🎉</h1>
                  <p>El servidor se encuentra funcionando correctamente</p>
              </div>
            </body>
            </html>

    - name: Configurar redirección del puerto 9091 al 80
      lineinfile:
        path: /etc/apache2/ports.conf
        line: "Listen 80"
        create: yes

    - name: Reiniciar Apache para aplicar cambios
      service:
        name: apache2
        state: restarted
